create table if not exists public.daily_goals_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  entry_date date not null,
  alert_type text not null,
  message text,
  status text,
  sent_at timestamptz default now()
);

create unique index if not exists daily_goals_notifications_unique
  on public.daily_goals_notifications (user_id, entry_date, alert_type);
